//! The results-matrix format and its generator.
//!
//! The honest unit of a conformance claim is *(corpus-id × terminal) → status*
//! (spec §10.2): several identifiers can pass on one emulator and fail on another,
//! so a single boolean would lie. This module defines a documented markdown shape
//! for that matrix and emits the **headless column** now. Real-terminal columns
//! are filled in later by the author via betamax; they are represented here as
//! empty columns the author replaces tape-by-tape.
//!
//! # Cell values
//!
//! | value  | meaning                                                            |
//! | ------ | ------------------------------------------------------------------ |
//! | `pass` | the behavior was observed on that terminal                         |
//! | `fail` | the behavior was expected but not observed                         |
//! | `na`   | not applicable / not decidable on that channel (e.g. a visual-only |
//! |        | case in the headless column) — never conflated with `pass`         |
//! | ` `    | (blank) not yet run on that terminal — the author fills it in      |
//!
//! # Shape
//!
//! One row per corpus id, one column per terminal, plus a leading `Asserts on`
//! column echoing the spec's channel so a reader sees why a headless `na` is
//! honest (a `screen`-only visual case cannot be judged from bytes).

use crate::corpus::Case;
use crate::runner::{Outcome, run_case};

/// The fixed header label for the headless column.
pub const HEADLESS_COLUMN: &str = "headless (vt100)";

/// Renders the results matrix as markdown, computing the headless column live and
/// leaving one blank column per name in `real_terminals` for the author to fill in
/// later via betamax.
///
/// The returned string is a complete markdown document: a title, the cell-value
/// legend, the matrix table, and a per-`na`/`fail` footnote block explaining each
/// non-pass headless cell (so the artifact is self-explaining).
#[must_use]
pub fn render_markdown(corpus: &[Case], real_terminals: &[&str]) -> String {
    let mut out = String::new();
    out.push_str("# Conformance results matrix\n\n");
    out.push_str(
        "Generated by `conformance`'s headless runner. The `headless (vt100)` column is \
         computed here; real-terminal columns are filled in by the author later via betamax \
         tapes (one column per emulator). See `README.md` for how to add a terminal.\n\n",
    );
    out.push_str("**Cell values:** `pass` observed · `fail` expected-but-not-observed · ");
    out.push_str("`na` not decidable on this channel (never conflated with `pass`) · ");
    out.push_str("blank = not yet run on that terminal.\n\n");

    // Header row.
    out.push_str("| Corpus ID | Asserts on | ");
    out.push_str(HEADLESS_COLUMN);
    out.push_str(" |");
    for term in real_terminals {
        out.push_str(&format!(" {term} |"));
    }
    out.push('\n');

    // Separator row.
    out.push_str("| --- | --- | --- |");
    for _ in real_terminals {
        out.push_str(" --- |");
    }
    out.push('\n');

    // Body + collect footnotes for any non-pass headless cell.
    let mut footnotes: Vec<(String, String)> = Vec::new();
    for case in corpus {
        let outcome = run_case(case);
        let status = outcome.matrix_status();
        let cell = match &outcome {
            Outcome::Pass => status.to_string(),
            Outcome::Fail(_) | Outcome::Skipped(_) => {
                // Mark the cell with a footnote reference.
                let marker = footnotes.len() + 1;
                match &outcome {
                    Outcome::Fail(msg) => {
                        footnotes.push((case.id.to_string(), format!("**fail:** {msg}")));
                    }
                    Outcome::Skipped(reason) => {
                        footnotes.push((
                            case.id.to_string(),
                            format!("**na (visual-only):** {reason}"),
                        ));
                    }
                    Outcome::Pass => unreachable!(),
                }
                format!("{status}[^{marker}]")
            }
        };
        out.push_str(&format!(
            "| `{}` | {} | {} |",
            case.id,
            case.channel.label(),
            cell
        ));
        for _ in real_terminals {
            out.push_str("  |");
        }
        out.push('\n');
    }

    if !footnotes.is_empty() {
        out.push('\n');
        for (i, (id, note)) in footnotes.iter().enumerate() {
            out.push_str(&format!("[^{}]: `{}` — {}\n", i + 1, id, note));
        }
    }

    out
}
